DEBUG    BddScenarioTests:abstract_tests_base.py:70 setup
DEBUG    BddScenarioTests:abstract_tests_base.py:63 initiating <class 'qa_pytest_commons.generic_steps.GenericSteps'>
DEBUG    GenericSteps:logger.py:130 >>> given  
DEBUG    GenericSteps:logger.py:143 <<< given
DEBUG    GenericSteps:logger.py:130 >>> nothing  
DEBUG    GenericSteps:logger.py:143 <<< nothing
DEBUG    GenericSteps:logger.py:130 >>> when  
DEBUG    GenericSteps:logger.py:143 <<< when
DEBUG    GenericSteps:logger.py:130 >>> when  
DEBUG    GenericSteps:logger.py:143 <<< when
DEBUG    GenericSteps:logger.py:130 >>> failing boom 
DEBUG    GenericSteps:before_sleep.py:65 Retrying tests.bdd_scenario_tests.BddScenarioTests.should_retry.<locals>.<lambda> in 1.0 seconds as it raised TestException: boom.
DEBUG    GenericSteps:logger.py:130 >>> when  
DEBUG    GenericSteps:logger.py:143 <<< when
DEBUG    GenericSteps:logger.py:130 >>> failing boom 
DEBUG    GenericSteps:before_sleep.py:65 Retrying tests.bdd_scenario_tests.BddScenarioTests.should_retry.<locals>.<lambda> in 2.0 seconds as it raised TestException: boom.
DEBUG    GenericSteps:logger.py:130 >>> when  
DEBUG    GenericSteps:logger.py:143 <<< when
DEBUG    GenericSteps:logger.py:130 >>> failing boom 
DEBUG    GenericSteps:before_sleep.py:65 Retrying tests.bdd_scenario_tests.BddScenarioTests.should_retry.<locals>.<lambda> in 4.0 seconds as it raised TestException: boom.
DEBUG    GenericSteps:logger.py:130 >>> when  
DEBUG    GenericSteps:logger.py:143 <<< when
DEBUG    GenericSteps:logger.py:130 >>> failing boom
DEBUG    BddScenarioTests:abstract_tests_base.py:76 teardown